# Generated by Django 3.2.5 on 2021-07-26 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='title')),
                ('text', models.TextField(default='', max_length=10000, verbose_name='text')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('request_type', models.CharField(choices=[('re', 'repair request'), ('se', 'service request'), ('co', 'consultation request')], default='', max_length=2, verbose_name='request type')),
                ('request_status', models.CharField(choices=[('op', 'open'), ('cl', 'close'), ('wo', 'at work')], default='op', max_length=2, verbose_name='request status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('worker', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='request_to_work', to=settings.AUTH_USER_MODEL, verbose_name='worker')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
                'permissions': [('view_requests_list', 'Can view requests list')],
            },
        ),
    ]
